/**
 * Flaha Agri Tech
 * Precision Agriculture Division
 * Copyright © 2026–2027 Flaha Agri Tech. All rights reserved.
 *
 * Title: Provider Framework Tests
 * Introduction: Verifies registry, selection, fallback, contracts, results, determinism, and security invariants.
 *
 * Created by: Rafat Al Khashan
 * Created date: 2026-07-16
 * Last modified: 2026-07-16
 */
import {createHash} from "node:crypto";import {describe,expect,it} from "vitest";import {assertArtifactReference,assertExecutionLimits,assertProviderDescriptor,assertProviderRequest,buildFallbackChain,BUILTIN_PROVIDER_CATALOGUE,DEFAULT_EXECUTION_LIMITS,FakeProviderAdapter,ProviderRegistry,providerError,selectProvider,validateProviderResult} from "../src/index.js";import type {ArtifactReference,ProviderDescriptor,ProviderRequest} from "../src/index.js";
const registry=()=>new ProviderRegistry(BUILTIN_PROVIDER_CATALOGUE);
const artifact:ArtifactReference={artifactId:"00000000-0000-4000-8000-000000000101",artifactClass:"RAW",role:"INPUT",key:"raw/sha256/aa/payload",mediaType:"application/pdf",byteLength:10,checksumAlgorithm:"SHA256",checksum:"a".repeat(64),immutable:true,createdAt:"2026-07-16T00:00:00.000Z"};
const base=(family:ProviderRequest["providerFamily"],capability:ProviderRequest["capability"],mediaType="application/pdf",languages:readonly string[]=["en"]):any=>({requestId:"request.one",providerFamily:family,capability,selectionPolicy:{requireProductionAuthorization:false},inputArtifact:artifact,mediaType,languageHints:languages,mode:"BENCHMARK",policySnapshot:{policyVersion:"1.0.0",networkPolicy:{mode:family.includes("ACQUISITION")?"EXACT_ORIGIN":"DENY_ALL",allowedOrigin:family.includes("ACQUISITION")?"https://example.test":undefined,maxRedirects:5,allowWebSockets:false},filesystemPolicy:{stagingNamespace:"staging",allowAbsolutePaths:false},resourcePolicy:{...DEFAULT_EXECUTION_LIMITS},languagePolicy:{allowedLanguages:[...languages],rejectUnsupported:true},contentPolicy:{allowEmbeddedArtifacts:false},artifactPolicy:{allowedKinds:["RAW","STAGING"],requireSha256:true}},executionLimits:{...DEFAULT_EXECUTION_LIMITS},provenanceContext:{correlationId:"correlation.one",causationId:null,selectionDecisionId:"selection.one"}});
const dataset=(capability="DATASET_ROW_VALIDATION")=>({...base("DATASET_VALIDATION",capability as any,"text/csv"),payload:{delimiter:",",hasHeader:true,expectedColumns:["id"]}}) as ProviderRequest;
const html=(capability="HTML_TEXT_EXTRACTION")=>({...base("HTML_EXTRACTION",capability as any,"text/html",["ar","en"]),payload:{extractText:true,extractLinks:true,extractMetadata:true,structuralMode:capability==="HTML_STRUCTURAL_EXTRACTION"?"DOM":"BASELINE"}}) as ProviderRequest;
const document=(capability="DOCUMENT_TEXT_EXTRACTION",languages:readonly string[]=["en"],inspectionOnly=false,media="application/pdf")=>({...base("DOCUMENT_PROCESSING",capability as any,media,languages),payload:{inspectionOnly,extractLayout:false,extractSections:false,extractTables:false,pageRange:null}}) as ProviderRequest;
const acquisition=(dynamic=false)=>({...base(dynamic?"BROWSER_ACQUISITION":"STATIC_ACQUISITION",dynamic?"JAVASCRIPT_RENDERING":"STATIC_HTTP_ACQUISITION","text/html",[]),selectionPolicy:{requireProductionAuthorization:false,...(dynamic?{dynamicRoutingSignal:"DYNAMIC_RENDER_REQUIRED"}: {})},governedSource:{scheme:"https",host:"example.test",port:443,relativeRoute:"/page"},payload:dynamic?{waitUntil:"NETWORK_IDLE",allowDownloads:false,allowPopups:false}:{obeyRobots:true,discoverLinks:true}}) as ProviderRequest;

describe("registry",()=>{it("constructs deterministically and queries indexes",()=>{const r=registry();expect(r.listProviders().map(x=>x.providerId)).toEqual([...r.listProviders().map(x=>x.providerId)].sort());expect(r.listProvidersForFamily("STATIC_ACQUISITION").map(x=>x.providerId)).toEqual(["acquisition.scrapy"]);expect(r.listProvidersForCapability("DOWNLOAD_DETECTION").map(x=>x.providerId)).toEqual(["acquisition.playwright"])});it("rejects duplicate IDs",()=>expect(()=>new ProviderRegistry([BUILTIN_PROVIDER_CATALOGUE[0]!,BUILTIN_PROVIDER_CATALOGUE[0]!])).toThrow(/duplicate/));it("rejects invalid descriptors",()=>expect(()=>assertProviderDescriptor({...BUILTIN_PROVIDER_CATALOGUE[0]!,providerId:"x;import('evil')"})).toThrow());it("returns immutable values",()=>expect(Object.isFrozen(registry().listProviders())).toBe(true));});
describe("selection",()=>{it("selects stdlib CSV primary",()=>expect(selectProvider(registry(),dataset()).selectedProviderId).toBe("dataset.csv.stdlib"));it("selects pandas only for tabular fallback",()=>expect(selectProvider(registry(),dataset("DATASET_TABULAR_FALLBACK")).selectedProviderId).toBe("dataset.tabular.pandas"));it("selects HTML baseline and structural providers",()=>{expect(selectProvider(registry(),html()).selectedProviderId).toBe("html.stdlib-htmlparser");expect(selectProvider(registry(),html("HTML_STRUCTURAL_EXTRACTION")).selectedProviderId).toBe("html.lxml")});it("selects Tika for English PDF text",()=>{const value=selectProvider(registry(),document());expect(value.selectedProviderId).toBe("document.apache-tika");expect(value.fallbackProviderIds).toEqual([])});it("has no provider for layout or table extraction",()=>{expect(selectProvider(registry(),document("DOCUMENT_TABLE_EXTRACTION")).status).toBe("NO_ELIGIBLE_PROVIDER");expect(selectProvider(registry(),document("DOCUMENT_LAYOUT_EXTRACTION")).status).toBe("NO_ELIGIBLE_PROVIDER")});it("selects Tika broad format fallback",()=>expect(selectProvider(registry(),document("DOCUMENT_BROAD_FORMAT_FALLBACK",["en"],false,"application/pdf")).selectedProviderId).toBe("document.apache-tika"));it("selects pypdf narrow inspection",()=>expect(selectProvider(registry(),document("DOCUMENT_INSPECTION",["en"],true)).selectedProviderId).toBe("document.pypdf-inspection"));it("rejects Arabic and bilingual document extraction",()=>{expect(selectProvider(registry(),document("DOCUMENT_TEXT_EXTRACTION",["ar"])).status).toBe("NO_ELIGIBLE_PROVIDER");expect(selectProvider(registry(),document("DOCUMENT_TEXT_EXTRACTION",["ar","en"])).selectionReason).toBe("UNSUPPORTED_LANGUAGE")});it("selects Scrapy static and Playwright dynamic",()=>{expect(selectProvider(registry(),acquisition()).selectedProviderId).toBe("acquisition.scrapy");expect(selectProvider(registry(),acquisition(true)).selectedProviderId).toBe("acquisition.playwright")});it("does not route ordinary static to Playwright",()=>{const request=acquisition(true) as any;delete request.selectionPolicy.dynamicRoutingSignal;expect(selectProvider(registry(),request).status).toBe("NO_ELIGIBLE_PROVIDER")});it("never selects deferred or rejected providers",()=>{expect(registry().getProvider("html.trafilatura")?.selectable).toBe(false);expect(registry().getProvider("document.pdfminer-six")?.selectable).toBe(false);expect(registry().getProvider("document.docling-slim")?.selectable).toBe(false)});it("enforces production authorization",()=>{const request=dataset() as any;request.selectionPolicy.requireProductionAuthorization=true;expect(selectProvider(registry(),request).status).toBe("NO_ELIGIBLE_PROVIDER")});});
describe("fallback",()=>{it("builds finite compatible deduplicated chains",()=>expect(buildFallbackChain(registry(),"html.stdlib-htmlparser",["html.lxml","html.lxml","acquisition.playwright"],"HTML_TEXT_EXTRACTION","PRIMARY_PROVIDER_TECHNICAL_FAILURE")).toEqual(["html.lxml"]));it("blocks terminal fallbacks",()=>{for(const reason of ["UNSUPPORTED_LANGUAGE","SECURITY_POLICY_VIOLATION","ARTIFACT_HASH_MISMATCH","PROVIDER_CONTRACT_VIOLATION"] as const)expect(buildFallbackChain(registry(),"document.apache-tika",["html.stdlib-htmlparser"],"DOCUMENT_TEXT_EXTRACTION",reason)).toEqual([])});});
describe("contracts and security",()=>{it("accepts valid requests and limits",()=>{expect(()=>assertProviderRequest(dataset())).not.toThrow();expect(()=>assertExecutionLimits({...DEFAULT_EXECUTION_LIMITS})).not.toThrow()});it("rejects invalid and shell-like IDs",()=>{for(const id of ["../x","x;cmd","x $(whoami)","import('x')"])expect(()=>assertProviderDescriptor({...BUILTIN_PROVIDER_CATALOGUE[0]!,providerId:id})).toThrow()});it("rejects artifact traversal, absolute paths, URLs and invalid hashes",()=>{for(const key of ["../x","/x","C:\\x","https://x"])expect(()=>assertArtifactReference({...artifact,relativeKey:key})).toThrow();expect(()=>assertArtifactReference({...artifact,sha256:"bad"})).toThrow()});it("rejects oversized, negative and nonfinite limits",()=>{for(const value of [-1,Infinity,99_999_999])expect(()=>assertExecutionLimits({...DEFAULT_EXECUTION_LIMITS,maxRedirects:value})).toThrow()});it("requires network policy for acquisition",()=>{const request=acquisition() as any;request.policySnapshot.networkPolicy.mode="DENY_ALL";expect(()=>assertProviderRequest(request)).toThrow(/NETWORK_POLICY/)});it("contains no environment or database escape hatches",()=>{const text=JSON.stringify(dataset());expect(text).not.toMatch(/DATABASE_URL|environment|credentials|providerOptions/)});});
describe("results, errors, adapters, and determinism",()=>{it("validates a bounded success",async()=>{const r=registry();const d=r.getProvider("dataset.csv.stdlib")!;const adapter=new FakeProviderAdapter(d,"SUCCESS");const request=dataset();const result=await adapter.execute(request,{executionId:"execution.one",signal:new AbortController().signal,stagingArtifacts:[],diagnosticLimitBytes:1000,runtimeEvidenceReference:null});expect(()=>validateProviderResult(result,request,d,"execution.one")).not.toThrow()});it("rejects wrong provider identity",async()=>{const d=registry().getProvider("dataset.csv.stdlib")!;const result=await new FakeProviderAdapter(d,"CONTRACT_VIOLATION").execute(dataset(),{executionId:"execution.one",signal:new AbortController().signal,stagingArtifacts:[],diagnosticLimitBytes:1,runtimeEvidenceReference:null});expect(()=>validateProviderResult(result,dataset(),d,"execution.one")).toThrow(/CONTRACT/)});it("declares error semantics",()=>{expect(providerError("PROVIDER_TIMEOUT","x")).toMatchObject({retryable:true,fallbackEligible:true,securityRelevant:false});expect(providerError("ARTIFACT_HASH_MISMATCH","x")).toMatchObject({retryable:false,fallbackEligible:false,securityRelevant:true})});it("supports unavailable and cancellable fakes",async()=>{const d=registry().getProvider("dataset.csv.stdlib")!;expect((await new FakeProviderAdapter(d,"UNAVAILABLE").checkAvailability()).status).toBe("UNAVAILABLE");const controller=new AbortController();const promise=new FakeProviderAdapter(d,"SLOW").execute(dataset(),{executionId:"x",signal:controller.signal,stagingArtifacts:[],diagnosticLimitBytes:1,runtimeEvidenceReference:null});controller.abort();await expect(promise).rejects.toThrow()});it("produces identical catalogue and selection hashes",()=>{const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");expect(hash(registry().listProviders())).toBe(hash(registry().listProviders()));expect(hash(selectProvider(registry(),document()))).toBe(hash(selectProvider(registry(),document())))});});
