/**
 * Flaha Agri Tech
 * Precision Agriculture Division
 * Copyright © 2026–2027 Flaha Agri Tech. All rights reserved.
 *
 * Title: Benchmark-Informed Provider Catalogue
 * Introduction: Catalogues accepted provider evidence without production authorization or runtime loading.
 *
 * Created by: Rafat Al Khashan
 * Created date: 2026-07-16
 * Last modified: 2026-08-19
 */
import type { CapabilitySupport, ProviderCapability, ProviderDescriptor, ProviderFamily, RuntimeKind } from "./types.js";
const evidence=(family:ProviderFamily,runtime:RuntimeKind,capability:ProviderCapability,status:CapabilitySupport["supportStatus"]="SUPPORTED",fallback:CapabilitySupport["fallbackSuitability"]="PRIMARY",languages:readonly string[]=["en"],mediaTypes?:readonly string[]):CapabilitySupport=>({capability,supportStatus:status,maturity:"BENCHMARKED",productionAuthorization:"NOT_AUTHORIZED",supportedMediaTypes:mediaTypes??(family==="DOCUMENT_PROCESSING"?["application/pdf"]:family==="HTML_EXTRACTION"?["text/html","application/xhtml+xml"]:family.includes("ACQUISITION")?["text/html","application/octet-stream"]:["text/csv"]),supportedLanguages:languages,constraints:[],knownLimitations:status==="SUPPORTED"?[]:["Benchmark evidence does not authorize this capability."],requiredRuntime:runtime,requiredPolicyFlags:family.includes("ACQUISITION")?["EXACT_ORIGIN"]:[],fallbackSuitability:fallback,evidenceReferences:["benchmarks/ingestion/reports/adoption-decision-register.md"]});
const descriptor=(providerId:string,providerFamily:ProviderFamily,displayName:string,implementationVersion:string,runtimeKind:RuntimeKind,lifecycleStatus:ProviderDescriptor["lifecycleStatus"],capabilities:CapabilitySupport[],selectable=true,network=false):ProviderDescriptor=>({providerId,providerFamily,displayName,implementationVersion,contractVersion:"1.0.0",runtimeKind,lifecycleStatus,productionAuthorization:"NOT_AUTHORIZED",supportedCapabilities:capabilities,supportedMediaTypes:[...new Set(capabilities.flatMap(c=>c.supportedMediaTypes))],supportedLanguages:[...new Set(capabilities.flatMap(c=>c.supportedLanguages))],executionModes:providerFamily==="BROWSER_ACQUISITION"?["BENCHMARK","DYNAMIC","FALLBACK"]:providerFamily==="STATIC_ACQUISITION"?["BENCHMARK","STATIC"]:["BASELINE","BENCHMARK","FALLBACK"],determinismLevel:"DETERMINISTIC",networkRequirement:network?"GOVERNED_REQUIRED":"DENY_ALL",artifactBehavior:providerFamily==="BROWSER_ACQUISITION"?["RAW_RESPONSE","RENDERED_HTML","OUTPUT_REFERENCE"]:providerFamily==="STATIC_ACQUISITION"?["RAW_RESPONSE","OUTPUT_REFERENCE"]:["INPUT_REFERENCE","OUTPUT_REFERENCE","STRUCTURED_OUTPUT"],selectable});
const htmlCaps:[ProviderCapability,...ProviderCapability[]]=["HTML_TEXT_EXTRACTION","HTML_LINK_EXTRACTION","HTML_METADATA_EXTRACTION","HTML_ENCODING_DETECTION"];
export const BUILTIN_PROVIDER_CATALOGUE:readonly ProviderDescriptor[]=Object.freeze([
 descriptor("acquisition.playwright","BROWSER_ACQUISITION","Playwright Chromium","1.61.1","BROWSER","HARDENED",[evidence("BROWSER_ACQUISITION","BROWSER","JAVASCRIPT_RENDERING","SUPPORTED","FALLBACK"),evidence("BROWSER_ACQUISITION","BROWSER","RENDERED_DOM_CAPTURE","SUPPORTED","FALLBACK"),evidence("BROWSER_ACQUISITION","BROWSER","BROWSER_NETWORK_INTERCEPTION","SUPPORTED","FALLBACK"),evidence("BROWSER_ACQUISITION","BROWSER","DOWNLOAD_DETECTION","SUPPORTED","FALLBACK"),evidence("BROWSER_ACQUISITION","BROWSER","POPUP_CONTAINMENT","SUPPORTED","FALLBACK")],true,true),
 descriptor("acquisition.scrapy","STATIC_ACQUISITION","Scrapy","2.17.0","PYTHON","HARDENED",["STATIC_HTTP_ACQUISITION","CONTROLLED_CRAWLING","LINK_DISCOVERY","ROBOTS_POLICY","REDIRECT_HANDLING","RETRY_HANDLING","RATE_LIMITING","RAW_RESPONSE_CAPTURE"].map(c=>evidence("STATIC_ACQUISITION","PYTHON",c as ProviderCapability)),true,true),
 descriptor("dataset.csv.stdlib","DATASET_VALIDATION","Python stdlib CSV validator","3.14","PYTHON","HARDENED",["DATASET_SCHEMA_INSPECTION","DATASET_ROW_VALIDATION","DATASET_TYPE_VALIDATION"].map(c=>evidence("DATASET_VALIDATION","PYTHON",c as ProviderCapability))),
 descriptor("dataset.tabular.pandas","DATASET_VALIDATION","pandas","2.3.3","PYTHON","BENCHMARKED",[evidence("DATASET_VALIDATION","PYTHON","DATASET_TABULAR_FALLBACK","SUPPORTED","FALLBACK")]),
 descriptor("document.apache-tika","DOCUMENT_PROCESSING","Apache Tika","3.3.1","JAVA","HARDENED",[evidence("DOCUMENT_PROCESSING","JAVA","DOCUMENT_TEXT_EXTRACTION","SUPPORTED","PRIMARY"),evidence("DOCUMENT_PROCESSING","JAVA","DOCUMENT_METADATA_EXTRACTION","SUPPORTED","FALLBACK"),evidence("DOCUMENT_PROCESSING","JAVA","DOCUMENT_BROAD_FORMAT_FALLBACK","SUPPORTED","PRIMARY",["en"],["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/rtf","text/rtf","text/plain"])]),
 descriptor("document.docling-slim","DOCUMENT_PROCESSING","Docling Slim","2.111.0","PYTHON","REJECTED",[evidence("DOCUMENT_PROCESSING","PYTHON","DOCUMENT_TEXT_EXTRACTION","UNSUPPORTED","NONE")],false),
 descriptor("document.pdfminer-six","DOCUMENT_PROCESSING","pdfminer.six","20260107","PYTHON","REJECTED",[evidence("DOCUMENT_PROCESSING","PYTHON","DOCUMENT_TEXT_EXTRACTION","UNSUPPORTED","NONE")],false),
 descriptor("document.pypdf-inspection","DOCUMENT_PROCESSING","pypdf inspection","6.14.2","PYTHON","BENCHMARKED",[evidence("DOCUMENT_PROCESSING","PYTHON","DOCUMENT_INSPECTION","PARTIALLY_SUPPORTED","PRIMARY"),evidence("DOCUMENT_PROCESSING","PYTHON","DOCUMENT_METADATA_EXTRACTION","PARTIALLY_SUPPORTED","PRIMARY"),evidence("DOCUMENT_PROCESSING","PYTHON","DOCUMENT_ANNOTATION_INVENTORY","PARTIALLY_SUPPORTED","PRIMARY"),evidence("DOCUMENT_PROCESSING","PYTHON","DOCUMENT_EMBEDDED_ARTIFACT_INVENTORY","PARTIALLY_SUPPORTED","PRIMARY")]),
 descriptor("html.lxml","HTML_EXTRACTION","lxml","6.1.1","PYTHON","BENCHMARKED",[...htmlCaps,"HTML_STRUCTURAL_EXTRACTION"].map(c=>evidence("HTML_EXTRACTION","PYTHON",c as ProviderCapability,"PARTIALLY_SUPPORTED","FALLBACK",["ar","en"]))),
 descriptor("html.selectolax","HTML_EXTRACTION","selectolax","0.4.10","PYTHON","BENCHMARKED",[...htmlCaps,"HTML_STRUCTURAL_EXTRACTION"].map(c=>evidence("HTML_EXTRACTION","PYTHON",c as ProviderCapability,"PARTIALLY_SUPPORTED","FALLBACK",["ar","en"]))),
 descriptor("html.stdlib-htmlparser","HTML_EXTRACTION","Python stdlib HTMLParser","3.14","PYTHON","HARDENED",htmlCaps.map(c=>evidence("HTML_EXTRACTION","PYTHON",c,"SUPPORTED","PRIMARY",["ar","en"]))),
 descriptor("html.trafilatura","HTML_EXTRACTION","Trafilatura","2.1.0","PYTHON","DEFERRED",[evidence("HTML_EXTRACTION","PYTHON","HTML_TEXT_EXTRACTION","DEFERRED","NONE")],false),
 descriptor("normalization.html.flaha-v1","HTML_EXTRACTION","Flaha HTML content normalizer","3J.1.0","IN_PROCESS","HARDENED",[evidence("HTML_EXTRACTION","IN_PROCESS","HTML_CONTENT_NORMALIZATION","SUPPORTED","PRIMARY",["en"],["text/html","application/xhtml+xml"])]),
 descriptor("normalization.document.flaha-v1","DOCUMENT_PROCESSING","Flaha document content normalizer","3J.1.0","IN_PROCESS","HARDENED",[evidence("DOCUMENT_PROCESSING","IN_PROCESS","DOCUMENT_CONTENT_NORMALIZATION","SUPPORTED","PRIMARY",["en"],["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/rtf","text/rtf","text/plain"])]),
]);
