/**
 * Flaha Agri Tech
 * Precision Agriculture Division
 * Copyright © 2026–2027 Flaha Agri Tech. All rights reserved.
 *
 * Title: Deterministic Provider Selection
 * Introduction: Applies benchmark-informed priorities and production-authorization gates.
 *
 * Created by: Rafat Al Khashan
 * Created date: 2026-07-16
 * Last modified: 2026-07-16
 */
import type { AvailabilityStatus, ProviderRequest, SelectionResult } from "./types.js"; import { assertProviderRequest } from "./validation.js"; import { ProviderRegistry } from "./registry.js";
const PRIORITY:Readonly<Record<string,readonly string[]>>={DATASET_SCHEMA_INSPECTION:["dataset.csv.stdlib"],DATASET_ROW_VALIDATION:["dataset.csv.stdlib"],DATASET_TYPE_VALIDATION:["dataset.csv.stdlib"],DATASET_TABULAR_FALLBACK:["dataset.tabular.pandas"],HTML_TEXT_EXTRACTION:["html.stdlib-htmlparser","html.lxml","html.selectolax"],HTML_LINK_EXTRACTION:["html.stdlib-htmlparser","html.lxml","html.selectolax"],HTML_METADATA_EXTRACTION:["html.stdlib-htmlparser","html.lxml","html.selectolax"],HTML_ENCODING_DETECTION:["html.stdlib-htmlparser","html.lxml","html.selectolax"],HTML_STRUCTURAL_EXTRACTION:["html.lxml","html.selectolax"],DOCUMENT_INSPECTION:["document.pypdf-inspection"],DOCUMENT_METADATA_EXTRACTION:["document.pypdf-inspection","document.apache-tika"],DOCUMENT_TEXT_EXTRACTION:["document.docling-slim","document.apache-tika"],DOCUMENT_LAYOUT_EXTRACTION:["document.docling-slim"],DOCUMENT_SECTION_EXTRACTION:["document.docling-slim"],DOCUMENT_TABLE_EXTRACTION:["document.docling-slim"],DOCUMENT_BROAD_FORMAT_FALLBACK:["document.apache-tika"],STATIC_HTTP_ACQUISITION:["acquisition.scrapy"],CONTROLLED_CRAWLING:["acquisition.scrapy"],LINK_DISCOVERY:["acquisition.scrapy"],ROBOTS_POLICY:["acquisition.scrapy"],REDIRECT_HANDLING:["acquisition.scrapy"],RETRY_HANDLING:["acquisition.scrapy"],RATE_LIMITING:["acquisition.scrapy"],RAW_RESPONSE_CAPTURE:["acquisition.scrapy"],JAVASCRIPT_RENDERING:["acquisition.playwright"],RENDERED_DOM_CAPTURE:["acquisition.playwright"],BROWSER_NETWORK_INTERCEPTION:["acquisition.playwright"],DOWNLOAD_DETECTION:["acquisition.playwright"],POPUP_CONTAINMENT:["acquisition.playwright"]};
export function selectProvider(registry:ProviderRegistry,request:ProviderRequest,availability:Readonly<Record<string,AvailabilityStatus>>={}):SelectionResult{assertProviderRequest(request);if(request.languageHints.some(l=>l.toLowerCase()==="ar")&&request.providerFamily==="DOCUMENT_PROCESSING"&&!request.payload.inspectionOnly)return{status:"NO_ELIGIBLE_PROVIDER",selectionReason:"UNSUPPORTED_LANGUAGE",candidateEvaluations:[],fallbackProviderIds:[],unavailableReasons:["Arabic/bilingual authoritative document extraction is unsupported."]};if(request.providerFamily==="BROWSER_ACQUISITION"&&request.selectionPolicy.dynamicRoutingSignal!=="DYNAMIC_RENDER_REQUIRED")return{status:"NO_ELIGIBLE_PROVIDER",selectionReason:"DYNAMIC_ROUTING_SIGNAL_REQUIRED",candidateEvaluations:[],fallbackProviderIds:[],unavailableReasons:["Playwright is not an automatic static fallback."]};let order=[...(PRIORITY[request.capability]??[])];if(request.selectionPolicy.preferredProviderId){if(!order.includes(request.selectionPolicy.preferredProviderId))return{status:"NO_ELIGIBLE_PROVIDER",selectionReason:"PREFERRED_PROVIDER_INCOMPATIBLE",candidateEvaluations:[],fallbackProviderIds:[],unavailableReasons:[request.selectionPolicy.preferredProviderId]};order=[request.selectionPolicy.preferredProviderId,...order.filter(x=>x!==request.selectionPolicy.preferredProviderId)]}const evaluations=order.map(id=>registry.evaluateProviderEligibility(id,{capability:request.capability,mediaType:request.mediaType,languages:request.languageHints,mode:request.mode,requireProductionAuthorization:request.selectionPolicy.requireProductionAuthorization,availability}));const selected=evaluations.find(e=>e.eligible);return selected?{status:"SELECTED",selectedProviderId:selected.providerId,selectionReason:"FIRST_ELIGIBLE_BY_CLOSED_PRIORITY",candidateEvaluations:evaluations,fallbackProviderIds:evaluations.filter(e=>e.eligible&&e.providerId!==selected.providerId).map(e=>e.providerId),unavailableReasons:evaluations.flatMap(e=>e.reasons)}:{status:"NO_ELIGIBLE_PROVIDER",selectionReason:"NO_ELIGIBLE_PROVIDER",candidateEvaluations:evaluations,fallbackProviderIds:[],unavailableReasons:evaluations.flatMap(e=>e.reasons)};}
