/**
 * Flaha Agri Tech
 * Precision Agriculture Division
 * Copyright © 2026–2027 Flaha Agri Tech. All rights reserved.
 *
 * Title: Provider Framework Validation
 * Introduction: Enforces strict descriptor, artifact, request, limit, and result boundaries.
 *
 * Created by: Rafat Al Khashan
 * Created date: 2026-07-16
 * Last modified: 2026-07-16
 */
import type { ArtifactReference, ExecutionLimits, ProviderDescriptor, ProviderExecutionResult, ProviderRequest } from "./types.js";

const ID=/^[a-z][a-z0-9]*(?:[.-][a-z0-9]+)*$/; const SHA=/^[a-f0-9]{64}$/; const MEDIA=/^[a-z0-9!#$&^_.+-]+\/[a-z0-9!#$&^_.+-]+$/i;
const MAX={wallTimeoutMs:3_600_000,startupTimeoutMs:300_000,maxInputBytes:10_737_418_240,maxOutputBytes:10_737_418_240,maxArtifacts:10_000,maxWarnings:10_000,maxErrors:1_000,maxChildProcesses:256,maxTemporaryBytes:21_474_836_480,maxPages:1_000_000,maxRows:100_000_000,maxColumns:100_000,maxRedirects:32,maxRetries:16,maxDepth:64,maxUrls:1_000_000,maxNetworkRequests:1_000_000,maxDownloads:1_000,maxPopups:1_000} satisfies Record<keyof ExecutionLimits,number>;
export const DEFAULT_EXECUTION_LIMITS:Readonly<ExecutionLimits>=Object.freeze({wallTimeoutMs:60_000,startupTimeoutMs:15_000,maxInputBytes:50_000_000,maxOutputBytes:100_000_000,maxArtifacts:100,maxWarnings:100,maxErrors:20,maxChildProcesses:16,maxTemporaryBytes:500_000_000,maxPages:1_000,maxRows:1_000_000,maxColumns:10_000,maxRedirects:5,maxRetries:2,maxDepth:3,maxUrls:1_000,maxNetworkRequests:2_000,maxDownloads:10,maxPopups:10});
export function assertArtifactReference(value:ArtifactReference):void {const allowed=new Set(["artifactId","artifactClass","role","key","mediaType","byteLength","checksumAlgorithm","checksum","immutable","createdAt"]);for(const key of Object.keys(value))if(!allowed.has(key))throw new Error(`ARTIFACT_REFERENCE_INVALID: unknown field ${key}`);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value.artifactId))throw new Error("ARTIFACT_REFERENCE_INVALID: artifactId");if(!MEDIA.test(value.mediaType))throw new Error("ARTIFACT_REFERENCE_INVALID: mediaType");if(!Number.isSafeInteger(value.byteLength)||value.byteLength<0)throw new Error("ARTIFACT_REFERENCE_INVALID: byteLength");if(value.checksumAlgorithm!=="SHA256"||!SHA.test(value.checksum))throw new Error("ARTIFACT_REFERENCE_INVALID: checksum");if(!value.key||value.key.includes("..")||value.key.includes("\\")||value.key.startsWith("/")||/^[a-z]+:/i.test(value.key)||value.key.includes(":"))throw new Error("ARTIFACT_REFERENCE_INVALID: key");if(!value.createdAt.endsWith("Z")||!Number.isFinite(Date.parse(value.createdAt)))throw new Error("ARTIFACT_REFERENCE_INVALID: createdAt"); }
export function assertExecutionLimits(value:ExecutionLimits):void { for(const [key,maximum] of Object.entries(MAX) as [keyof ExecutionLimits,number][]) {const current=value[key]; if(!Number.isSafeInteger(current)||current<0||current>maximum)throw new Error(`INVALID_PROVIDER_REQUEST: ${key}`)} }
export function assertProviderDescriptor(value:ProviderDescriptor):void { if(!ID.test(value.providerId))throw new Error("invalid providerId"); if(value.contractVersion!=="1.0.0"||!value.displayName||!value.implementationVersion)throw new Error("invalid descriptor identity"); if(value.productionAuthorization==="AUTHORIZED"||value.supportedCapabilities.some(c=>c.maturity==="PRODUCTION_READY"||c.productionAuthorization==="AUTHORIZED"))throw new Error("Phase 3F descriptors cannot be production authorized"); const seen=new Set<string>(); for(const support of value.supportedCapabilities){if(seen.has(support.capability))throw new Error("duplicate capability"); seen.add(support.capability); if(support.requiredRuntime!==value.runtimeKind)throw new Error("contradictory runtime"); if(support.supportStatus==="UNSUPPORTED"&&support.fallbackSuitability!=="NONE")throw new Error("unsupported capability cannot be selectable")} if(value.selectable&&["DISABLED","REJECTED","DEFERRED"].includes(value.lifecycleStatus))throw new Error("inactive descriptor cannot be selectable"); }
export function assertProviderRequest(request:ProviderRequest):void { const acquisition=request.providerFamily==="STATIC_ACQUISITION"||request.providerFamily==="BROWSER_ACQUISITION";const allowed=new Set(["requestId","providerFamily","capability","requestedProviderId","selectionPolicy","inputArtifact","mediaType","languageHints","mode","policySnapshot","executionLimits","provenanceContext","payload",...(acquisition?["governedSource"]:[])]);for(const key of Object.keys(request))if(!allowed.has(key))throw new Error(`INVALID_PROVIDER_REQUEST: unknown field ${key}`);if(!ID.test(request.requestId))throw new Error("INVALID_PROVIDER_REQUEST: requestId");if(request.requestedProviderId&&!ID.test(request.requestedProviderId))throw new Error("INVALID_PROVIDER_REQUEST: requestedProviderId");if(request.selectionPolicy.preferredProviderId&&!ID.test(request.selectionPolicy.preferredProviderId))throw new Error("INVALID_PROVIDER_REQUEST: preferredProviderId");if(!["BASELINE","BENCHMARK","STATIC","DYNAMIC","INSPECTION","FALLBACK"].includes(request.mode))throw new Error("INVALID_PROVIDER_REQUEST: mode");if(!MEDIA.test(request.mediaType))throw new Error("INVALID_PROVIDER_REQUEST: mediaType");assertExecutionLimits(request.executionLimits);if(request.inputArtifact)assertArtifactReference(request.inputArtifact);if(request.capability.startsWith("STATIC_")&&request.providerFamily!=="STATIC_ACQUISITION")throw new Error("INVALID_PROVIDER_REQUEST: family capability mismatch");if(request.capability.startsWith("JAVASCRIPT_")&&request.providerFamily!=="BROWSER_ACQUISITION")throw new Error("INVALID_PROVIDER_REQUEST: family capability mismatch");if(acquisition&&request.policySnapshot.networkPolicy.mode!=="EXACT_ORIGIN")throw new Error("NETWORK_POLICY_VIOLATION"); }
export function validateProviderResult<T>(result:ProviderExecutionResult<T>,request:ProviderRequest,selected:ProviderDescriptor,executionId:string):ProviderExecutionResult<T>{ if(result.providerId!==selected.providerId||result.providerVersion!==selected.implementationVersion||result.contractVersion!==selected.contractVersion||result.capability!==request.capability||result.requestId!==request.requestId||result.executionId!==executionId||result.policyVersion!==request.policySnapshot.policyVersion)throw new Error("PROVIDER_CONTRACT_VIOLATION"); if(Date.parse(result.completedAt)<Date.parse(result.startedAt)||!Number.isFinite(Date.parse(result.startedAt)))throw new Error("PROVIDER_CONTRACT_VIOLATION: timestamps"); if(result.warnings.length>request.executionLimits.maxWarnings)throw new Error("PROVIDER_OUTPUT_INVALID: warnings"); if(result.outcome==="SUCCESS"){if(result.artifacts.length>request.executionLimits.maxArtifacts)throw new Error("PROVIDER_OUTPUT_INVALID: artifacts"); let total=0; for(const artifact of result.artifacts){assertArtifactReference(artifact); total+=artifact.byteLength} if(total>request.executionLimits.maxOutputBytes||result.metrics.outputBytes!==total)throw new Error("PROVIDER_OUTPUT_INVALID: output bytes");} return result; }
