/**
 * Flaha Agri Tech
 * Precision Agriculture Division
 * Copyright © 2026–2027 Flaha Agri Tech. All rights reserved.
 *
 * Title: Acquisition Workflow Application Service
 * Introduction:
 * Creates governed acquisition jobs and executes one claimed adapter attempt through Phase 3G lifecycle and canonical artifacts.
 *
 * Created by: Rafat Al Khashan
 * Created date: 2026-07-16
 * Last modified: 2026-08-21
 */
import type { PrismaClient } from "@prisma/client"; import type { FilesystemArtifactStore } from "@flaha-intel/artifact-store"; import { DEFAULT_EXECUTION_LIMITS, type ArtifactReference, type ProviderError, type ProviderExecutionResult, type ProviderRequest } from "@flaha-intel/ingestion-provider-core";
import { IngestionJobService } from "../ingestionJobs/service.js"; import type { AcquisitionAdapter, AcquisitionArtifactAllocation, AcquisitionCommand, AcquisitionLimits, ArtifactRole, ControlledCrawlCommand, DynamicAcquisitionCommand, GovernedLocator } from "./contracts.js"; import { validateLocator } from "./networkPolicy.js";
const max=(value:number,limit:number,name:string)=>{if(!Number.isSafeInteger(value)||value<0||value>limit)throw new Error(`INVALID_ACQUISITION_LIMIT: ${name}`);return value};
function validateLimits(value:AcquisitionLimits){max(value.maxDepth,16,"maxDepth");max(value.maxUrls,1000,"maxUrls");max(value.maxRedirects,16,"maxRedirects");max(value.maxNetworkRequests,5000,"maxNetworkRequests");max(value.maxDownloads,100,"maxDownloads");max(value.maxPopups,100,"maxPopups");max(value.maxResponseBytes,100_000_000,"maxResponseBytes");if(value.wallTimeoutMs<1000||value.wallTimeoutMs>300_000)throw new Error("INVALID_ACQUISITION_LIMIT: wallTimeoutMs")}
const policy=(locator:GovernedLocator,limits:AcquisitionLimits)=>({policyVersion:"3H.1",networkPolicy:{mode:"EXACT_ORIGIN" as const,allowedOrigin:`${locator.scheme}://${locator.host}:${locator.port}`,maxRedirects:limits.maxRedirects,allowWebSockets:false},filesystemPolicy:{stagingNamespace:"acquisition",allowAbsolutePaths:false as const},resourcePolicy:{...DEFAULT_EXECUTION_LIMITS,wallTimeoutMs:limits.wallTimeoutMs,maxOutputBytes:limits.maxResponseBytes*4,maxArtifacts:8,maxRedirects:limits.maxRedirects,maxDepth:limits.maxDepth,maxUrls:limits.maxUrls,maxNetworkRequests:limits.maxNetworkRequests,maxDownloads:limits.maxDownloads,maxPopups:limits.maxPopups},languagePolicy:{allowedLanguages:[] as string[],rejectUnsupported:true as const},contentPolicy:{allowEmbeddedArtifacts:false},artifactPolicy:{allowedKinds:["RAW","EVIDENCE"] as const,requireSha256:true as const}});
export class AcquisitionWorkflowService{
  private readonly jobs:IngestionJobService; constructor(private readonly db:PrismaClient,private readonly artifacts:FilesystemArtifactStore,private readonly adapters:ReadonlyMap<string,AcquisitionAdapter>){this.jobs=new IngestionJobService(db)}
  private async create(command:AcquisitionCommand,capability:"STATIC_HTTP_ACQUISITION"|"CONTROLLED_CRAWLING"|"LINK_DISCOVERY"|"JAVASCRIPT_RENDERING"|"RENDERED_DOM_CAPTURE",dynamic:boolean){validateLimits(command.limits);await validateLocator(command.locator);const snapshot=policy(command.locator,command.limits);const request:any={requestId:`acquisition.${command.idempotencyKey}`,providerFamily:dynamic?"BROWSER_ACQUISITION":"STATIC_ACQUISITION",capability,selectionPolicy:{requireProductionAuthorization:false,...(dynamic?{dynamicRoutingSignal:"DYNAMIC_RENDER_REQUIRED"}: {})},mediaType:"text/html",languageHints:[],mode:dynamic?"DYNAMIC":"STATIC",policySnapshot:snapshot,executionLimits:{...snapshot.resourcePolicy,...command.executionLimits},provenanceContext:{correlationId:command.actor.correlationId,causationId:null,selectionDecisionId:`selection.${command.idempotencyKey}`},governedSource:{scheme:command.locator.scheme,host:command.locator.host,port:command.locator.port,relativeRoute:command.locator.relativeRoute},payload:dynamic?{waitUntil:"NETWORK_IDLE",allowDownloads:(command as DynamicAcquisitionCommand).allowDownloads,allowPopups:false}:{obeyRobots:true,discoverLinks:capability!=="STATIC_HTTP_ACQUISITION"}};return this.jobs.createIngestionJob({jobType:request.providerFamily,idempotencyKey:command.idempotencyKey,priority:command.priority,request,sourceLocator:{kind:"GOVERNED_ACQUISITION",scheme:command.locator.scheme,host:command.locator.host,port:command.locator.port,relativeRoute:command.locator.relativeRoute,fixture:command.locator.mode==="FIXTURE"},actor:command.actor})}
  createStaticAcquisitionJob(command:AcquisitionCommand){return this.create(command,"STATIC_HTTP_ACQUISITION",false)}
  createControlledCrawlJob(command:ControlledCrawlCommand){return this.create(command,command.capability,false)}
  createDynamicBrowserAcquisitionJob(command:DynamicAcquisitionCommand){if(command.routingSignal!=="DYNAMIC_RENDER_REQUIRED")throw new Error("DYNAMIC_RENDER_REQUIRED");return this.create(command,command.capability,true)}
  requestCancellation(jobId:string,reason:string,actor:AcquisitionCommand["actor"]){return this.jobs.requestCancellation(jobId,reason,actor)}
  async runClaimedAcquisitionAttempt(workerId:string,actor:AcquisitionCommand["actor"],beforeProviderLaunch?: (jobId:string)=>Promise<void>){
    const capabilities=["STATIC_HTTP_ACQUISITION","CONTROLLED_CRAWLING","LINK_DISCOVERY","JAVASCRIPT_RENDERING","RENDERED_DOM_CAPTURE"];
    const claim=await this.jobs.claimNextJob(workerId,capabilities,60_000,actor);if(!claim)return null;
    await this.jobs.startAttempt(claim.job.id,claim.attempt.id,claim.leaseToken,actor);
    const owner={jobId:claim.job.id,attemptId:claim.attempt.id}; const allocations:AcquisitionArtifactAllocation[]=[]; const promoted:{reference:ArtifactReference;role:string}[]=[];
    const cleanup=async(diagnostic:string)=>{for(const allocation of allocations){const metadata=await this.artifacts.metadata(allocation.artifactId).catch(()=>null);if(!metadata)continue;if(["ALLOCATED"].includes(metadata.state))await this.artifacts.abandon(metadata.artifactId,owner,diagnostic).catch(()=>undefined);else if(["WRITING","SEALED","VERIFIED"].includes(metadata.state))await this.artifacts.quarantine(metadata.artifactId,owner,diagnostic).catch(()=>undefined)}};
    const initial=await this.db.ingestionJob.findUnique({where:{id:claim.job.id},select:{state:true}});if(initial?.state==="CANCEL_REQUESTED"){await this.jobs.acknowledgeCancellation(claim.job.id,claim.attempt.id,claim.leaseToken,actor);return {jobId:claim.job.id,outcome:"CANCELLED" as const}}
    const adapter=this.adapters.get(claim.attempt.providerId);if(!adapter)throw new Error("Selected acquisition adapter is unavailable.");
    const request=claim.job.requestEnvelope as unknown as ProviderRequest;const locatorValue=claim.job.sourceLocator as any;const locator:GovernedLocator={mode:locatorValue.fixture?"FIXTURE":"PUBLIC",scheme:locatorValue.scheme,host:locatorValue.host,port:locatorValue.port,relativeRoute:locatorValue.relativeRoute};
    const limits:AcquisitionLimits={maxDepth:request.executionLimits.maxDepth,maxUrls:request.executionLimits.maxUrls,maxRedirects:request.executionLimits.maxRedirects,maxNetworkRequests:request.executionLimits.maxNetworkRequests,maxDownloads:request.executionLimits.maxDownloads,maxPopups:request.executionLimits.maxPopups,maxResponseBytes:request.executionLimits.maxOutputBytes/4,wallTimeoutMs:request.executionLimits.wallTimeoutMs};
    const roles:Array<{role:ArtifactRole;mediaType:string;maximumBytes:number}>=[{role:"RAW_RESPONSE",mediaType:"text/html",maximumBytes:limits.maxResponseBytes},...(adapter.providerId==="acquisition.playwright"?[{role:"RENDERED_HTML" as const,mediaType:"text/html",maximumBytes:limits.maxResponseBytes}]:[]),{role:"METADATA",mediaType:"application/json",maximumBytes:Math.min(1_000_000,limits.maxResponseBytes)},{role:"RESULT",mediaType:"application/json",maximumBytes:Math.min(1_000_000,limits.maxResponseBytes)}];
    for(const role of roles){const allocated=await this.artifacts.allocateGenerated(owner,role.maximumBytes);await this.artifacts.beginExternalWrite(allocated.artifactId,owner);allocations.push({artifactId:allocated.artifactId,role:role.role,mediaType:role.mediaType,stagingKey:allocated.stagingKey,maximumBytes:role.maximumBytes})}
    await beforeProviderLaunch?.(claim.job.id);const beforeLaunch=await this.db.ingestionJob.findUnique({where:{id:claim.job.id},select:{state:true}});if(beforeLaunch?.state==="CANCEL_REQUESTED"){await cleanup("Cancelled before provider execution.");await this.jobs.acknowledgeCancellation(claim.job.id,claim.attempt.id,claim.leaseToken,actor);return {jobId:claim.job.id,outcome:"CANCELLED" as const}}
    const controller=new AbortController();let heartbeatError:unknown;const timer=setInterval(()=>{void (async()=>{try{const state=await this.db.ingestionJob.findUnique({where:{id:claim.job.id},select:{state:true}});if(state?.state==="CANCEL_REQUESTED")controller.abort();else await this.jobs.heartbeatAttempt(claim.job.id,claim.attempt.id,claim.leaseToken)}catch(error){heartbeatError=error;controller.abort()}})()},100);timer.unref();
    try{
      const outcome=await adapter.execute({jobId:claim.job.id,attemptId:claim.attempt.id,capability:request.capability as any,locator,limits,allocations,workingDirectory:this.artifacts.governedRootPath(),signal:controller.signal});if(heartbeatError)throw heartbeatError;
      if(outcome.outcome!=="SUCCESS"){await cleanup(outcome.message);if(outcome.outcome==="CANCELLED"){await this.jobs.acknowledgeCancellation(claim.job.id,claim.attempt.id,claim.leaseToken,actor);return {jobId:claim.job.id,outcome:"CANCELLED" as const}}const reroute=outcome.code==="DYNAMIC_RENDER_REQUIRED";await this.jobs.failAttempt(claim.job.id,claim.attempt.id,claim.leaseToken,{code:outcome.code,message:outcome.message,retryable:Boolean(outcome.retryable),fallbackEligible:false,securityRelevant:Boolean(outcome.securityRelevant)} as ProviderError,actor);return {jobId:claim.job.id,outcome:reroute?"DYNAMIC_RENDER_REQUIRED" as const:"FAILED" as const}}
      for(const captured of outcome.artifacts){const sealed=await this.artifacts.sealExternalWrite(captured.artifactId,owner,captured.byteLength,captured.checksum);await this.artifacts.verify(sealed.artifactId,owner);await this.jobs.heartbeatAttempt(claim.job.id,claim.attempt.id,claim.leaseToken);const prefix={RAW_RESPONSE:"raw",RENDERED_HTML:"rendered",METADATA:"metadata",RESULT:"result",DIAGNOSTIC:"diagnostic"}[captured.role];const final=await this.artifacts.promote({artifactId:sealed.artifactId,...owner,finalKey:`${prefix}/sha256/${sealed.checksum}`});promoted.push({role:captured.role,reference:{artifactId:final.artifactId,artifactClass:captured.role==="RAW_RESPONSE"?"RAW":"EVIDENCE",role:captured.role==="RENDERED_HTML"?"MARKDOWN":captured.role==="METADATA"?"MANIFEST":"OUTPUT",key:final.finalKey!,mediaType:captured.mediaType,byteLength:final.byteLength!,checksumAlgorithm:"SHA256",checksum:final.checksum!,immutable:true,createdAt:final.createdAt}})}
      await this.jobs.heartbeatAttempt(claim.job.id,claim.attempt.id,claim.leaseToken);const now=new Date().toISOString();const result:ProviderExecutionResult<unknown>={outcome:"SUCCESS",providerId:adapter.providerId,providerVersion:adapter.providerVersion,contractVersion:"1.0.0",capability:request.capability,executionId:claim.attempt.id,requestId:request.requestId,warnings:[],metrics:{startupDurationMs:0,executionDurationMs:1,totalDurationMs:1,inputBytes:0,outputBytes:promoted.reduce((sum,x)=>sum+x.reference.byteLength,0),temporaryBytes:0,warningCount:0,artifactCount:promoted.length},provenance:{providerId:adapter.providerId,providerVersion:adapter.providerVersion,contractVersion:"1.0.0",capability:request.capability,policyVersion:request.policySnapshot.policyVersion,inputArtifactHashes:[],outputArtifactHashes:promoted.map(x=>x.reference.checksum),selectionDecision:request.provenanceContext.selectionDecisionId,fallbackHistory:[],runtimeEvidenceReference:outcome.evidence.runtimeEvidence,determinismClassification:"DETERMINISTIC"},policyVersion:request.policySnapshot.policyVersion,startedAt:claim.attempt.startedAt?.toISOString()??now,completedAt:now,artifacts:promoted.map(x=>x.reference),structuredOutput:outcome.evidence,error:null};await this.jobs.completeAttempt(claim.job.id,claim.attempt.id,claim.leaseToken,result,actor);return {jobId:claim.job.id,outcome:"SUCCESS" as const,artifacts:promoted.map(x=>x.reference)}
    }catch(error){await cleanup("Late or rejected acquisition output.");const message=error instanceof Error?error.message.slice(0,500):"Acquisition output failed governed verification.";try{await this.jobs.failAttempt(claim.job.id,claim.attempt.id,claim.leaseToken,{code:"PROVIDER_OUTPUT_INVALID",message,retryable:true,fallbackEligible:false,securityRelevant:false},actor);return {jobId:claim.job.id,outcome:"FAILED" as const}}catch{throw error}}finally{clearInterval(timer)}
  }
}
