/**
 * Flaha Agri Tech
 * Precision Agriculture Division
 * Copyright © 2026–2027 Flaha Agri Tech. All rights reserved.
 *
 * Title: Extraction Routing Internal CLI
 * Introduction: Provides bounded creation, execution, and safe inspection of internal extraction jobs.
 *
 * Created by: Rafat Al Khashan
 * Created date: 2026-07-16
 * Last modified: 2026-07-16
 */
import path from "node:path";
import {FilesystemArtifactRepository,FilesystemArtifactStore} from "@flaha-intel/artifact-store";
import {DEFAULT_EXECUTION_LIMITS,type ArtifactReference} from "@flaha-intel/ingestion-provider-core";
import {prisma} from "../db.js";import {IngestionJobService} from "../ingestionJobs/service.js";
import {SupervisedExtractionAdapter} from "./adapters.js";import type {ExtractionAdapter,ExtractionCapability} from "./contracts.js";import {ExtractionWorkflowService} from "./service.js";
const allowed=new Set<ExtractionCapability>(["HTML_TEXT_EXTRACTION","HTML_METADATA_EXTRACTION","HTML_LINK_EXTRACTION","HTML_STRUCTURAL_EXTRACTION","DOCUMENT_TEXT_EXTRACTION","DOCUMENT_LAYOUT_EXTRACTION","DOCUMENT_SECTION_EXTRACTION","DOCUMENT_TABLE_EXTRACTION","DOCUMENT_DIGITAL_TEXT_ASSESSMENT","DOCUMENT_BROAD_FORMAT_FALLBACK","DOCUMENT_INSPECTION","DOCUMENT_METADATA_EXTRACTION","DOCUMENT_ANNOTATION_INVENTORY","DOCUMENT_EMBEDDED_ARTIFACT_INVENTORY"]),priorities=new Set(["LOW","NORMAL","HIGH","CRITICAL"]);
const args:Record<string,string>={};for(let i=3;i<process.argv.length;i+=2){const key=process.argv[i];if(!key?.startsWith("--")||process.argv[i+1]===undefined)throw new Error("Arguments must be bounded --name value pairs.");args[key.slice(2)]=process.argv[i+1]}
const acceptedArgs=new Set(["artifact-id","capability","languages","idempotency-key","priority","max-input-bytes","max-output-bytes","max-artifacts","timeout-ms","actor-id","correlation-id","worker-id","job-id"]);for(const key of Object.keys(args))if(!acceptedArgs.has(key))throw new Error(`Unsupported argument: ${key}`);
const rootPath=path.resolve(import.meta.dirname,"../../../.."),artifactRoot=path.resolve(process.env.FLAHA_ARTIFACT_ROOT??path.join(rootPath,".flaha-artifacts")),repository=new FilesystemArtifactRepository(artifactRoot);await repository.initialize();const store=new FilesystemArtifactStore(artifactRoot,repository);await store.initialize();const script=path.join(rootPath,"apps/ingest-worker/src/extraction_worker.py"),schemas=path.join(rootPath,"packages/ingestion-contracts/schemas/v1");
const specs:[string,string,string][]=[["html.stdlib-htmlparser","3.14",path.join(rootPath,"C:/Python314/python.exe")],["html.lxml","6.1.1",path.join(rootPath,".benchmark-envs/html-lxml-6.1.1-py314/Scripts/python.exe")],["html.selectolax","0.4.10",path.join(rootPath,".benchmark-envs/html-selectolax-0.4.10-py314/Scripts/python.exe")],["document.docling-slim","2.111.0",path.join(rootPath,".benchmark-envs/document-docling-slim-2.111.0-py314/Scripts/python.exe")],["document.apache-tika","3.3.1","C:/Python314/python.exe"],["document.pypdf-inspection","6.14.2",path.join(rootPath,".benchmark-envs/document-pypdf-6.14.2-py314/Scripts/python.exe")]];
const adapters=new Map<string,ExtractionAdapter>(specs.map(([id,version,executable])=>{const adapter=new SupervisedExtractionAdapter(id,version,{executable:id==="html.stdlib-htmlparser"?"C:/Python314/python.exe":executable,script,schemas});return[id,adapter]})),workflow=new ExtractionWorkflowService(prisma,store,adapters),command=process.argv[2],actor={type:"ADMIN" as const,id:args["actor-id"]??"extraction.cli",correlationId:args["correlation-id"]??`extraction.cli.${Date.now()}`};
const bounded=(name:string,fallback:number,min:number,max:number)=>{const value=args[name]===undefined?fallback:Number(args[name]);if(!Number.isSafeInteger(value)||value<min||value>max)throw new Error(`Invalid ${name}.`);return value};
try{if(command==="create"){const artifactId=args["artifact-id"],capability=args.capability as ExtractionCapability;if(!artifactId||!/^[0-9a-f-]{36}$/i.test(artifactId)||!allowed.has(capability)||!args["idempotency-key"])throw new Error("Canonical artifact ID, allowed capability, and idempotency key are required.");if(args.priority&&!priorities.has(args.priority))throw new Error("Invalid priority.");const metadata=await store.metadata(artifactId),link=await prisma.ingestionArtifactLink.findFirstOrThrow({where:{artifactId},orderBy:{createdAt:"desc"}});if(metadata.state!=="PROMOTED"||!metadata.finalKey||!metadata.byteLength||!metadata.checksum)throw new Error("Artifact is not canonical.");const input:ArtifactReference={artifactId,artifactClass:link.relationship==="RAW_RESPONSE"?"RAW":"EVIDENCE",role:link.relationship==="RENDERED_HTML"?"OUTPUT":"INPUT",key:metadata.finalKey,mediaType:link.mediaType,byteLength:Number(link.byteSize),checksumAlgorithm:"SHA256",checksum:link.sha256,immutable:true,createdAt:metadata.createdAt};const executionLimits={...DEFAULT_EXECUTION_LIMITS,maxInputBytes:bounded("max-input-bytes",DEFAULT_EXECUTION_LIMITS.maxInputBytes,1,100_000_000),maxOutputBytes:bounded("max-output-bytes",DEFAULT_EXECUTION_LIMITS.maxOutputBytes,1,100_000_000),maxArtifacts:bounded("max-artifacts",DEFAULT_EXECUTION_LIMITS.maxArtifacts,1,8),wallTimeoutMs:bounded("timeout-ms",DEFAULT_EXECUTION_LIMITS.wallTimeoutMs,1000,300_000)};const data={inputArtifact:input,mediaType:link.mediaType,capability,languageHints:(args.languages??"").split(",").filter(Boolean),idempotencyKey:args["idempotency-key"],priority:(args.priority??"NORMAL") as "NORMAL",executionLimits,actor};const job=capability.startsWith("HTML_")?await workflow.createHtmlExtractionJob(data):await workflow.createDocumentExtractionJob(data);console.log(JSON.stringify({id:job.id,state:job.state,selectedProviderId:job.selectedProviderId}))}
else if(command==="worker-once")console.log(JSON.stringify(await workflow.runClaimedExtractionAttempt(args["worker-id"]??"extraction.cli.worker",actor)));
else if(command==="job"){const jobs=new IngestionJobService(prisma),job=await jobs.getJob(args["job-id"]),attempts=await jobs.listJobAttempts(args["job-id"]),transitions=await jobs.listJobTransitions(args["job-id"]),artifacts=await prisma.ingestionArtifactLink.findMany({where:{jobId:args["job-id"]},select:{artifactId:true,attemptId:true,relationship:true,mediaType:true,sha256:true,byteSize:true,createdAt:true}}),provenance=await prisma.ingestionProvenance.findMany({where:{jobId:args["job-id"]},select:{providerId:true,providerVersion:true,capability:true,policyVersion:true,inputHashes:true,outputHashes:true,determinismClassification:true,createdAt:true}});console.log(JSON.stringify({job,attempts,transitions,artifacts:artifacts.map(a=>({...a,byteSize:a.byteSize.toString()})),provenance}))}
else if(command==="artifact"){const value=await store.metadata(args["artifact-id"]);console.log(JSON.stringify({artifactId:value.artifactId,state:value.state,byteLength:value.byteLength,checksum:value.checksum,createdAt:value.createdAt,updatedAt:value.updatedAt}))}else throw new Error("Expected create, worker-once, job, or artifact.")}finally{await prisma.$disconnect()}
