/**
 * Flaha Agri Tech
 * Precision Agriculture Division
 * Copyright © 2026–2027 Flaha Agri Tech. All rights reserved.
 *
 * Title: Extraction Routing Application Service
 * Introduction: Routes immutable canonical artifacts through durable supervised extraction attempts.
 *
 * Created by: Rafat Al Khashan
 * Created date: 2026-07-16
 * Last modified: 2026-07-16
 */
import type {PrismaClient} from "@prisma/client";
import type {FilesystemArtifactStore} from "@flaha-intel/artifact-store";
import {DEFAULT_EXECUTION_LIMITS,type ArtifactReference,type ProviderError,type ProviderExecutionResult,type ProviderRequest} from "@flaha-intel/ingestion-provider-core";
import {IngestionJobService} from "../ingestionJobs/service.js";
import type {ExtractionAdapter,ExtractionAllocation,ExtractionCapability,ExtractionCommand,ExtractionRole} from "./contracts.js";
const html=new Set(["text/html","application/xhtml+xml"]),docs=new Set(["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","application/vnd.openxmlformats-officedocument.presentationml.presentation","application/rtf","text/rtf","text/plain"]),inputRoles=new Set(["INPUT","RAW_RESPONSE","RENDERED_HTML","OUTPUT"]);
const roles=(cap:string):Array<[ExtractionRole,string]>=>[...(cap.match(/INSPECTION|METADATA|INVENTORY/)?[]:[["EXTRACTED_TEXT","text/markdown"] as [ExtractionRole,string]]),["METADATA","application/json"],...(cap.match(/STRUCTURAL|LAYOUT|SECTION|INSPECTION|INVENTORY/)?[["STRUCTURE","application/json"] as [ExtractionRole,string]]:[]),...(cap.includes("TABLE")?[["TABLE","application/json"] as [ExtractionRole,string]]:[]),["RESULT","application/json"]];
const finalRole=(r:ExtractionRole):ArtifactReference["role"]=>({EXTRACTED_TEXT:"MARKDOWN",METADATA:"MANIFEST",STRUCTURE:"STRUCTURED",TABLE:"TABLE",RESULT:"OUTPUT",DIAGNOSTIC:"LOG"})[r] as ArtifactReference["role"];
export class ExtractionWorkflowService{
 private jobs:IngestionJobService;constructor(private db:PrismaClient,private store:FilesystemArtifactStore,private adapters:ReadonlyMap<string,ExtractionAdapter>){this.jobs=new IngestionJobService(db)}
 private async verify(a:ArtifactReference,media:string,limit:number){if(a.mediaType!==media||!a.immutable||a.checksumAlgorithm!=="SHA256"||!inputRoles.has(a.role)||a.byteLength>Math.min(limit,100_000_000)||a.key.includes("..")||a.key.startsWith("/")||/^[A-Za-z]:/.test(a.key))throw new Error("INVALID_EXTRACTION_INPUT");await this.store.verifyPromotedPath(a.artifactId,a.byteLength,a.checksum)}
 private async create(c:ExtractionCommand,family:"HTML_EXTRACTION"|"DOCUMENT_PROCESSING"){if(!(family==="HTML_EXTRACTION"?html:docs).has(c.mediaType))throw new Error("UNSUPPORTED_MEDIA");const limits={...DEFAULT_EXECUTION_LIMITS,...c.executionLimits};await this.verify(c.inputArtifact,c.mediaType,limits.maxInputBytes);const payload=family==="HTML_EXTRACTION"?{extractText:true,extractLinks:true,extractMetadata:true,structuralMode:c.capability.includes("STRUCTURAL")?"DOM" as const:"BASELINE" as const}:{inspectionOnly:c.capability.includes("INSPECTION")||c.capability.includes("INVENTORY"),extractLayout:c.capability.includes("LAYOUT"),extractSections:c.capability.includes("SECTION"),extractTables:c.capability.includes("TABLE"),pageRange:null};const request={requestId:`extraction.${c.idempotencyKey}`,providerFamily:family,capability:c.capability,selectionPolicy:{requireProductionAuthorization:false},mediaType:c.mediaType,languageHints:c.languageHints,mode:c.mode??"BASELINE",policySnapshot:{policyVersion:"3I.1",networkPolicy:{mode:"DENY_ALL",maxRedirects:0,allowWebSockets:false},filesystemPolicy:{stagingNamespace:"extraction",allowAbsolutePaths:false},resourcePolicy:limits,languagePolicy:{allowedLanguages:c.languageHints,rejectUnsupported:true},contentPolicy:{allowEmbeddedArtifacts:false},artifactPolicy:{allowedKinds:["NORMALIZED","EVIDENCE"],requireSha256:true}},executionLimits:limits,provenanceContext:{correlationId:c.actor.correlationId,causationId:null,selectionDecisionId:`selection.${c.idempotencyKey}`},inputArtifact:c.inputArtifact,payload} as unknown as ProviderRequest;return this.jobs.createIngestionJob({jobType:family,idempotencyKey:c.idempotencyKey,priority:c.priority,request,sourceLocator:{kind:"ARTIFACT_ONLY",artifactId:c.inputArtifact.artifactId},actor:c.actor})}
 createHtmlExtractionJob(c:ExtractionCommand){return this.create(c,"HTML_EXTRACTION")}createDocumentExtractionJob(c:ExtractionCommand){return this.create(c,"DOCUMENT_PROCESSING")}createDocumentInspectionJob(c:ExtractionCommand){return this.create(c,"DOCUMENT_PROCESSING")}requestCancellation(id:string,reason:string,actor:ExtractionCommand["actor"]){return this.jobs.requestCancellation(id,reason,actor)}
 async runClaimedExtractionAttempt(worker:string,actor:ExtractionCommand["actor"],beforeLaunch?:(id:string)=>Promise<void>){const caps:ExtractionCapability[]=["HTML_TEXT_EXTRACTION","HTML_METADATA_EXTRACTION","HTML_LINK_EXTRACTION","HTML_STRUCTURAL_EXTRACTION","DOCUMENT_TEXT_EXTRACTION","DOCUMENT_LAYOUT_EXTRACTION","DOCUMENT_SECTION_EXTRACTION","DOCUMENT_TABLE_EXTRACTION","DOCUMENT_DIGITAL_TEXT_ASSESSMENT","DOCUMENT_BROAD_FORMAT_FALLBACK","DOCUMENT_INSPECTION","DOCUMENT_METADATA_EXTRACTION","DOCUMENT_ANNOTATION_INVENTORY","DOCUMENT_EMBEDDED_ARTIFACT_INVENTORY"];const claim=await this.jobs.claimNextJob(worker,caps,60_000,actor);if(!claim)return null;await this.jobs.startAttempt(claim.job.id,claim.attempt.id,claim.leaseToken,actor);const req=claim.job.requestEnvelope as unknown as ProviderRequest,input=req.inputArtifact!,owner={jobId:claim.job.id,attemptId:claim.attempt.id},allocs:ExtractionAllocation[]=[],outputs:ArtifactReference[]=[];
  const cleanup=async(reason:string)=>{for(const a of allocs){const m=await this.store.metadata(a.artifactId).catch(()=>null);if(m?.state==="ALLOCATED")await this.store.abandon(a.artifactId,owner,reason).catch(()=>{});else if(m&&["WRITING","SEALED","VERIFIED"].includes(m.state))await this.store.quarantine(a.artifactId,owner,reason).catch(()=>{})}};
  try{await this.verify(input,req.mediaType,req.executionLimits.maxInputBytes);if((await this.db.ingestionJob.findUnique({where:{id:claim.job.id},select:{state:true}}))?.state==="CANCEL_REQUESTED"){await this.jobs.acknowledgeCancellation(claim.job.id,claim.attempt.id,claim.leaseToken,actor);return{outcome:"CANCELLED" as const}}
   const adapter=this.adapters.get(claim.attempt.providerId);if(!adapter)throw new Error("SELECTED_PROVIDER_UNAVAILABLE");for(const [role,mediaType] of roles(req.capability)){const maximumBytes=Math.min(req.executionLimits.maxOutputBytes,25_000_000),a=await this.store.allocateGenerated(owner,maximumBytes);await this.store.beginExternalWrite(a.artifactId,owner);allocs.push({artifactId:a.artifactId,role,mediaType,stagingKey:a.stagingKey,maximumBytes})}await beforeLaunch?.(claim.job.id);if((await this.db.ingestionJob.findUnique({where:{id:claim.job.id},select:{state:true}}))?.state==="CANCEL_REQUESTED"){await cleanup("Cancelled before launch");await this.jobs.acknowledgeCancellation(claim.job.id,claim.attempt.id,claim.leaseToken,actor);return{outcome:"CANCELLED" as const}}
   const controller=new AbortController();let heartbeatError:unknown;const timer=setInterval(()=>void(async()=>{try{const state=(await this.db.ingestionJob.findUnique({where:{id:claim.job.id},select:{state:true}}))?.state;if(state==="CANCEL_REQUESTED")controller.abort();else await this.jobs.heartbeatAttempt(claim.job.id,claim.attempt.id,claim.leaseToken)}catch(e){heartbeatError=e;controller.abort()}})(),100);timer.unref();try{const result=await adapter.execute({jobId:claim.job.id,attemptId:claim.attempt.id,capability:req.capability as ExtractionCapability,inputArtifact:input,policyVersion:req.policySnapshot.policyVersion,limits:req.executionLimits,languageHints:[...req.languageHints],allocations:allocs,workingDirectory:this.store.governedRootPath(),signal:controller.signal});if(heartbeatError)throw heartbeatError;if(result.outcome!=="SUCCESS"){await cleanup(result.message);if(result.outcome==="CANCELLED"){await this.jobs.acknowledgeCancellation(claim.job.id,claim.attempt.id,claim.leaseToken,actor);return{outcome:"CANCELLED" as const}}await this.jobs.failAttempt(claim.job.id,claim.attempt.id,claim.leaseToken,{code:result.code as ProviderError["code"],message:result.message,retryable:result.retryable,fallbackEligible:result.fallbackEligible,securityRelevant:result.securityRelevant},actor);return{outcome:"FAILED" as const}}
    for(const o of result.artifacts){const sealed=await this.store.sealExternalWrite(o.artifactId,owner,o.byteLength,o.checksum);await this.store.verify(sealed.artifactId,owner);await this.jobs.heartbeatAttempt(claim.job.id,claim.attempt.id,claim.leaseToken);const p=await this.store.promote({artifactId:o.artifactId,...owner,finalKey:`${o.role.toLowerCase()}/sha256/${sealed.checksum}/${o.artifactId}`});outputs.push({artifactId:p.artifactId,artifactClass:o.role==="EXTRACTED_TEXT"?"NORMALIZED":"EVIDENCE",role:finalRole(o.role),key:p.finalKey!,mediaType:o.mediaType,byteLength:p.byteLength!,checksumAlgorithm:"SHA256",checksum:p.checksum!,immutable:true,createdAt:p.createdAt})}
    const now=new Date().toISOString(),wire:ProviderExecutionResult<unknown>={outcome:"SUCCESS",providerId:adapter.providerId,providerVersion:adapter.providerVersion,contractVersion:"1.0.0",capability:req.capability,executionId:claim.attempt.id,requestId:req.requestId,warnings:[],metrics:{startupDurationMs:0,executionDurationMs:1,totalDurationMs:1,inputBytes:input.byteLength,outputBytes:outputs.reduce((n,a)=>n+a.byteLength,0),temporaryBytes:0,warningCount:0,artifactCount:outputs.length},provenance:{providerId:adapter.providerId,providerVersion:adapter.providerVersion,contractVersion:"1.0.0",capability:req.capability,policyVersion:req.policySnapshot.policyVersion,inputArtifactHashes:[input.checksum],outputArtifactHashes:outputs.map(a=>a.checksum),selectionDecision:req.provenanceContext.selectionDecisionId,fallbackHistory:[],runtimeEvidenceReference:result.runtimeEvidence,determinismClassification:"DETERMINISTIC"},policyVersion:req.policySnapshot.policyVersion,startedAt:claim.attempt.startedAt?.toISOString()??now,completedAt:now,artifacts:outputs,structuredOutput:result.evidence,error:null};await this.jobs.completeAttempt(claim.job.id,claim.attempt.id,claim.leaseToken,wire,actor);return{outcome:"SUCCESS" as const,artifacts:outputs}}finally{clearInterval(timer)}
  }catch(error){await cleanup("Rejected or stale extraction output");try{await this.jobs.failAttempt(claim.job.id,claim.attempt.id,claim.leaseToken,{code:"PROVIDER_OUTPUT_INVALID",message:"Extraction output failed governed verification.",retryable:false,fallbackEligible:false,securityRelevant:true},actor);return{outcome:"FAILED" as const}}catch{throw error}}
 }
}
